// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
. . . . . . . . . f f f f f . . 
. . . . . . . . f 1 1 1 1 1 f . 
. . . . . . . . f 1 1 1 1 1 f . 
. . . . . . . f 1 1 1 1 1 1 f . 
. . . . . . . f 1 1 f 1 1 1 f . 
. . . . f f f f 1 1 f 1 1 1 f . 
. . . f 1 1 d f 1 1 f f f f . . 
. . f 1 1 1 d f 1 1 f 1 f . . . 
. f f 1 1 1 d f 1 1 f 1 f . . . 
f 1 1 1 1 1 1 d f f 1 1 f . . . 
f 1 1 1 1 1 1 1 1 1 1 1 f . . . 
. f f 1 1 1 1 1 1 1 1 1 f . . . 
. . f d 1 1 1 1 1 1 1 1 f . . . 
. . f d 1 1 1 1 1 1 1 d f . . . 
. . . f d d d d d d d f . . . . 
. . . . f f f f f f f . . . . . 
`;
            case "image2":return img`
........................
..........bbbb..........
........bbddddbb........
.......bddbbbbddb.......
......bdbbddddbbdb......
.....bdbbdbbbbdbbdb.....
.....bdbdbddddbdbdb.....
.....cdbbdbbbbdbbdc.....
.....cbdbbddddbbdbc.....
.....efbddbbbbddbce.....
.....eeffbddddbccee.....
.....eeeeffcccceee......
.....ceeeeeeeeeeee......
.....ceeeeeeeeeeee......
.....feeeeeeeeeeee......
.....cceeeeeeeeeee......
......feeeeeeeeeee......
.....6fceeeeeeeeee6.....
....6776eeeeeeeee676....
...6777666eeee6666776...
..67768e67766777667776..
...668ee7768867788666...
......ee77eeee77ecee....
......ee6eeeeee6eef.....
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
